rtfeldman/elm-css

.travis.yml, appveyor.yml, examples/src/HomepageStylesheet.elm, index.js, package.json, src/Css.elm, src/Emitter.elm, templates/emitter/Emitter.elm, templates/emitter/elm-package.json, test/emit.js, test/fixtures/homepage-compiled.css
* Now you can do `var emit = require("elm-css")` to get a function which takes a source .elm file and a destination .css file and returns a promise which generates the latter from the former.
* Stylesheets can now expose just the return value of `stylesheet`, not a `Result String String`
* Css.elm no longer knows about `CompilerOutput`; that's all in `templates/` now, for use exclusively in the Node wrapper
* There's a basic test that asserts this all works for HomepageStylesheet
=> Expose emitting API

index.html, src/Css.elm
This makes a lot more things type-checkable.
Definitely introduced regressions around `initial` and the like (see https://github.com/rtfeldman/elm-css/issues/48), but worth switching over now and fixing those later so that new work can use the new system.
=> Revamp type hierarchy to use extensible records

src/Css.elm
`align-itmems` -> `align-items`
=> Fix typos in Css.elm docs

src/Css/Colors.elm
Inspired by @mgold's [tweet](https://twitter.com/maxgoldst/status/694344712266911744), this makes it so elm-css ships with default colors from [clrs.cc](http://clrs.cc).
```elm
import Css.Colors exposing (..)
stylesheet
[ button
[ backgroundColor blue ]
]
```
...compiles to:
```css
button {
backgroundColor: #0074D9;
}
```
=> Add Colors.elm for a nice default set of colors

README.md, examples/README.md, index.js
- Adds a high-level README to the examples folder
- Adds useful error messages for when you've given the cli tool a bad entry file, e.g
- Adds useful error messages for when you've given the cli tool a file without any ports
- Adds useful error messages for when you've given a cli tool a file with ports of a different name
- Adds useful error message for the type of the port was wrong
=> WIP: Examples fixes and make the CLI tool more elm-y

README.md, examples/src/SharedStyles.elm, src/Html/CssHelpers.elm
Instead of adding `rules`, just resolve the collision by renaming `CssHelpers.namespace` to `CssHelpers.withNamespace`
=> Resolve collision

src/Css.elm
(have "#……") ,so some codeIDE can colored on them
=> make hex function can preprocess "#2B414D" like color String 

src/Css.elm, test/Fixtures.elm, test/Tests.elm
I've been looking to get into Elm, and this project seems a great effort to be able to reduce the errors in writing CSS in combination with Elm.
The first item in issue #32 , validation checks are asked for hex values. I have implemented these.
Any feedback is very much welcome as I'm still learning!
=> Add hex color validations

Tutorial.md
Hey @rtfeldman, 
First of all, thanks for elm-css... I really like css-modules but this takes it even further! :grinning: 
I was trying to learn how to do media queries with the tutorial and notice that there are some things that might be outdated. 
Those things are:
-  `with hover` for `hover`
-  `with media "print"` to `withMedia [ print ]`
What I don't know how to fix, and no longer work is: 
- `with ((.) Large) `
-  `with ((#) SignUp)`
Should it be `withClass ((.) Large)` ?
Cheers,
Nacho
=> A couple of fixes on the Tutorial

Tutorial.md, src/Css/Structure/Output.elm, test/Fixtures.elm, test/Tests.elm
Hey @rtfeldman, 
I just noticed that the output of  media queries had a syntax error(extra quotes). The output of media queries now is:
```css
@media "print"{
}
// or 
@media "screen and (max-width: 400px)" {
}
```
and the correct syntax according to the [spec](https://developer.mozilla.org/es/docs/CSS/Media_queries) is this one:
```css
@media print{
}
// or 
@media screen and (max-width: 400px) {
}
```
I changed it, updated the docs and the tests.
Let me know if code looks good and sorry for not catching this error in the previous PR. 
Cheers,
=> remove quotes on media queries

examples/elm-package.json, examples/src/SharedStyles.elm, examples/src/Stylesheets.elm, index.js
Due to the changes in the port system on both the JavaScript and Elm
side the cli application was no longer able to extract the generated
CSS from the Elm appliation.
This commit fixes the issue in the CLI and updates the example code so
the two work together again.
Resolves #120.
Some comments:
- I had to include elm-css-util in the examples elm-package.json as well, or I'd get an error that Css.Helpers could not be found.
- The one way I could figure out to publish a command now was to create a complete Program and send the command as part of the Program's init step. The one Program currently available is `Html.App`, so that's the one I used. Does someone know an easier way?
- The JavaScript generated by Elm now self-exports `Elm` on `module.exports`.
=> Fix elm-css cli for Elm version 0.17.

src/Css.elm
This was replaced with 'int' in commit: 660c8b29ec292cbfb7c62ea4d4037e097be00756
=> Correcting some docstrings that refer to the obsolete 'n' function.

README.md, readme-example/elm-package.json, readme-example/src/Main.elm, readme-example/src/MyCss.elm, readme-example/src/Stylesheets.elm
This updates the `Stylesheets` module in the readme.
I also updated the `readme-example` to make it work with Elm v0.17.
resolves #130
=> fixes generation of css in readme/example

src/Css/Preprocess/Resolve.elm, src/Css/Structure.elm
See issue #129. This implements resolving of pseudo **elements** (like, before/after).
The test suite is undergoing maintenance right now, so I have not been able to get those working (#135).
I do have results by changing `examples/HomepageCss.elm` and compiling it to CSS. I changed the bottom style block to:
```elm
, (#) BuyTickets
[ padding (px 16)
, paddingLeft (px 24)
, paddingRight (px 24)
, marginLeft (px 50)
, marginRight auto
, color (rgb 255 255 255)
, backgroundColor (rgb 27 217 130)
, verticalAlign middle
, descendants
[ nav
[ color (hex "#aaa")
, before
[ color (hex "#bbb") ]
, after
[ color (hex "#ccc") ]
]
]
, before
[ color (hex "#ddd") ]
]
```
And the output of this becomes:
```css
#BuyTickets {
padding: 16px;
padding-left: 24px;
padding-right: 24px;
margin-left: 50px; …
```
=> Resolve pseudo elements

src/Css/Structure/Output.elm
Right now compiled CSS with pseudo elements looks like `.selector ::before {}`. This space before the pseudo element is misinterpreted by browsers. This whole rule will apply `::before` to `.selector`'s children.
=> Remove space before pseudo element in compiled CSS

src/Css/Preprocess/Resolve.elm, test/Fixtures.elm, test/Tests.elm
This PR aims to fix issue #136 .
The issue was: when resolving multiple sibling pseudo classes like:
```elm
[ a 
[ color (hex "#000")
, hover
[ color (hex "#111") ]
, active
[ color (hex "#222") ]
, disabled
[ color (hex "#333") ]
]
]
```
the code written would resolve `a`, and next up, it would resolve `a:hover` and since `:hover` is a complete new styleblock definition, it got appended to the list of styleblock declarations. What happens next is that `:active` would get resolved, but since the latest styleblock is now an `a:hover`, it would think it's a nested pseudo class.
I have fixed this issue, by popping the last declaration, and using that to resolve pseudo classes. And in the end, using `List.tail` to get rid of the `a` declaration. This seems to fix my issues, and the issue …
=> Resolve multiple sibling pseudo classes correctly

examples/elm-package.json
I was unable to build the examples with Elm 0.17.1 until I relaxed the elm-version constraint.
While doing that I also relaxed the core constraint to allow the new 4.0.x releases.
=> Update example dependencies to run on Elm 0.17.1

README.md, readme-example/src/Main.elm
In the readme example, shouldn't the `id` function be taking a single identifier for the css ID instead of a list? I understand that it still works as a list, but it seems more normal to have it as a single identifier, and it may otherwise cause some head-scratching for newcomers (as it did with me).
This PR contains the needed changes if you agree.
=> Readme/example: Change ID from list to single item

examples/elm-package.json, src/Css/Preprocess/Resolve.elm, test/Fixtures.elm, test/Tests.elm
This is a follow-up on #142 that aims to fix the comment in issue #136 .
I added a compare that checks if the first declaration matches the one from the parent. If it does not match, it means that variable `rest` had an `AppendProperty` that should belong to the parent. If so, we replace the last declaration inside the `declarations` variable with the changed one.
=> Fix properties not resolving after or inbetween an ExtendSelector and/or WithPseudoElement

src/Css/Preprocess/Resolve.elm, src/Css/Structure.elm, test/Fixtures.elm, test/Tests.elm
This attempts to fix issue #140 .
While working on the fix, [I noticed that `mapLast` is used instead of `List.map`](https://github.com/rtfeldman/elm-css/blob/7c58295a3b21efc6b7a6904e64df36bf36a58529/src/Css/Structure.elm#L259) when resolving chained pseudo classes. @rtfeldman even though I changed it to `List.map`, I can't figure out if it's a correct assumption that `mapLast` was at fault here. Could I have regressed something by changing it to `List.map`? I've thought about it, and couldn't find a scenario that would fail tests.
Also, while working on it, I realised the same issue applied to pseudo *elements*, so I fixed that as well, and introduced a nice refactor to remove some duplication.
Thoughts and concerns? :)
=> Fix pseudo elements and classes not resolving when chained with `each` 

examples/src/Stylesheets.elm, src/Css.elm, src/Css/File.elm, src/Css/Preprocess/Resolve.elm, test/Compile.elm, test/CompileFixtures.elm, test/TestUtil.elm
I'm open to rename the function, but I wasn't sure what the convention was for describing an _n_ number of arguments. Maybe it's something like `compileN`?
=> Add support for compiling many stylesheets

src/Css.elm, test/Properties.elm
This aims to fix issue #148 . [The CSS spec](https://developer.mozilla.org/nl/docs/Web/CSS/color) allows color to assume the following global values:
```css
/* Global values */
color: inherit;
color: initial;
color: unset;
```
=> Allow color to be inherit, unset and initial

src/Css.elm, test/Properties.elm
This implements the `outline` property (and co).
Even though the CSS spec of `outline` does not mention this (for some weird reason), but browsers accept `outline: 0` as well. So I made it also accept `outline zero`. It is also properly configured to accept the global values `initial`, `inherit` and `unset`.
=> outline, outline-width, outline-style, outline-color and outline-offset properties

elm-css.js, index.js
This allows to automate elm-css compilation in a encapsulated environment - 
where installing elm globally is not possible. For instance, on Heroku.
=> Allow to specify (optional) path to elm-make

Tutorial.md, src/Css.elm
As per the suggestion I received in https://github.com/rtfeldman/elm-css/issues/158, this PR fixes a tiny error in the tutorial. Since I came across that error by searching for a way to set fonts by their name (like "Helvetica" instead of sansSerif or whatever), I took the liberty of adding a bit of documentation to `fontFamily` pointing to `fontFamilies`, since that's the first place I went looking. After all, the CSS property is called `font-family`, and there is no `font-families` one.
=> Improve font documentation and fix tutorial error

src/Css.elm, tests/Properties.elm
* Replace `float` with `num` so `float` can be used for stuff like `float: right` 😅
* Add type aliases for `Px`, `Em`, etc.
=> Improve length units

.travis.yml, src/Css.elm, tests/Fixtures.elm, tests/Tests.elm
**NOTE: I believe this is ready to merge! Please see my bottom-most comment.**
This PR is not yet ready to merge. I'm looking for some feedback to finish it and though this might be useful for discussion.
I've been working on the background keywords (issue #16) and have completed most of the grunt work. However, some issues remain that I'd appreciate some help with. I'm still pretty new to Elm, so please have some patience with me :).
The `background-repeat` property allows the value `round` which shadows `Basics.round`. It's unfortunate, but personally I think its best to leave it this way and have users type `Css.round` if they want to use it. The alternative of giving it another name I personally think would create more confusion then it solves. Do you agree?
The …
=> Background keywords (#16) (WIP)

README.md
Including a link to elm-css-normalize, which is a nice package if you want to use Normalize.css with elm-css without extra build tools or manual steps.
=> Add a readme section for related projects

README.md
Hey guys. Current version of README contains an outdated example of Stylesheets module which cost me some time of head scratching to understand why it was impossible to use `elm-css` as described in the file. Frustrating experience.
Stylesheets module in the `examples` folder is working exactly according to the description so I think it makes sense to put this working code excerpt into README as well.
Thanks for great job. :-)
=> Add working code example to illustrate elm-css approach

src/Css.elm, tests/Properties.elm, tests/Selectors.elm
adressing #183 
The basic table properties were implemented, but not exposed. This
PR adds
* table
* inlineTable
* tableCell
* tableRow
* tableColumn
* tableCaption
* tableRowGroup
* tableColumnGroup
* tableHeaderGroup
* tableFooterGroup
and their associated tests
further notes:
* `table` is already a selector (the table html
element) and thus `display table` will have to become `display Css.table` in
most actual use cases where elm-css is imported as `exposing (..)`. A specific `displayTable` property (analogous todisplayFlex) is a possible fix.
* In the comments, I've changed the text in the link to the css value instead of the elm-css value (`inline-table` instead of `inlineTable`). This is consistent with other links to the MDN documentation. 
* Is the ordering of the properties …
=> Add `display:table` and its derivatives

examples/src/HomepageCss.elm, readme-example/src/MyCss.elm, src/Css.elm, tests/CompileFixtures.elm, tests/Fixtures.elm, tests/Selectors.elm
💥 Big breaking change! 💥
This has been a long time coming, but it seems like the right choice:
Replace `(.)` with `class` and `(#)` with `id`.
Even though these are nicer names, I've avoided doing this because I wanted to avoid namespace clashes in the case where you're defining styles in the same file as some view code, and you have `import Css exposing (..)` and `import Html.Attributes exposing (..)` in the same file.
However, what I realized is that:
1. This already comes up with stuff like `src`, and if you do `import Html.Attributes as Attr exposing (..)` followed by `Attr.src` to disambiguate and resolve the compiler error, it's not a huge deal.
2. In practice, if you're writing views and styles in the same file, you're probably shadowing `class` anyway using a namespace helper …
=> 💥 Rename (.) to class and (#) to id 💥

elm-package.json, examples/elm-package.json, readme-example/elm-package.json, src/Css.elm, tests/Colors.elm, tests/Compile.elm, tests/Tests.elm, tests/elm-package.json
Fixes https://github.com/rtfeldman/elm-css/issues/203 and also fixes the same thing for `hsla`.
=> Fix hex and hsla color mixing

elm-css.js
Commander will automatically include the program name in the usage
information, so including it here means it is duplicated in the final
output like this:
```
$ elm-css -h
Usage: elm-css elm-css PATH # path to your Stylesheets.elm file
Options:
[ etc ]
```
=> Remove duplicated program name in elm-css usage

src/Css.elm
Fixing a small typo I found while searching in the docs this afternoon.
=> correct typos in docs for |/| and |*| functions

.travis.yml
I noticed that builds on travis were failing because files inside of `node_modules` were being run through `elm-format`.
Hope this helps! Thanks!
=> Avoid validating formatting of node_modules

src/Css.elm
Add the :visited pseudo-class, useful for when you want to differentiate from links that have been visited and ones that have not.
=> Add :visited pseudo-class

README.md
I recently started using `elm-css`, and lacking a reason to choose one approach over the other I defaulted to using the first approach. After briefly discussing the differences with @rtfeldman on the Elm Slack a
while back, I decided that the second approach would better suit me. This is an attempt to briefly document the functional differences between the two approaches to hopefully help others make this choice.
I've also added some formatting while editing the `README`. Thanks!
=> Add brief reasons for different elm-css usage approaches

src/Css.elm, tests/Fixtures.elm, tests/Tests.elm
First off, if this was already a thing and I just couldn't figure it out, my bad, just close this :)
This adds and exposes two functions - `pseudoElement` and `pseudoClass` - that teach take a `String` and a `List Mixin` and returns a `Mixin`. This lets people use custom elements and classes that aren't included in `elm-css` for some reason.
I also refactored the current definitions to use these functions instead.
Kind of a response to #239 being closed, but it also feels like something that should be available regardless. :)
Hope the tests were satisfactory (see "extant") this time? I figured that the current tests already tested the refactoring, so I just added tests for using the functions explicitly.
=> Add functions for custom pseudo-elements and pseudo-classes

src/Css.elm, tests/Properties.elm
The type signature was incorrect (didn't allow mixing length units on the first two arguments, so e.g., `borderRadius4 (em 0.2) (px 3) (px5) (px5)` was invalid.
=> Fix borderRadius4

src/Css.elm, tests/Properties.elm
Add borderWidth through borderWidth4 functions, for using the `border-width` property without specifying side.
=> Add borderWidth functions

src/Css.elm, src/Css/Elements.elm, src/Css/Namespace.elm, src/Css/Preprocess.elm, src/Css/Preprocess/Resolve.elm, tests/Fixtures.elm, tests/Properties.elm, tests/Selectors.elm, tests/Tests.elm
It's always been pretty weird that `backgroundColor` returns something called `Mixin`. My thinking was "these work like Mixins from Sass/Stylus/etc" but really what I want to say is just "these compose" and calling them Mixins seems unnecessary in retrospect.
What I should have said in the first place was "`backgroundColor` returns a `Style`, and you can compose `Style`s to make other `Style`s"
=> Rename `Mixin` to `Style`

src/Css.elm, tests/Properties.elm
This PR:
- adds tests for the `text-transform` properties already supported;
- adds support for the `none` property for `text-transform` (fixing https://github.com/rtfeldman/elm-css/issues/244);
- adds support for `inherit`, `initial`, and `unset` properties for `text-transform`, which I noticed https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform also says should be supported.
Hope this helps :slightly_smiling_face:.
=> Support more `text-transform` values

src/Css/Elements.elm, tests/Selectors.elm
`dl`, `dt` and `dd` elements are missing
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dt
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dd
=> Add dl, dt and dd elements

src/Css.elm
This commit adds a new method, `touchAction`, and all the values
supported by the `touch-action` property [1]:
* `panX`
* `panLeft`
* `panRight`
* `panY`
* `panUp`
* `panDown`
* `pinchZoom`
* `manipulation`
As explained in this post "More Responsive Tapping on iOS" [2] on
the WebKit blog, "WebKit on iOS has a 350 millisecond delay before
single taps activate links or buttons. [...] Since double tapping is
defined as two taps within a short time interval (350ms), WebKit must
wait for this time interval to pass before we’re sure that the user
intended to tap only once.".
Thanks to `touch-action`, and more specifically when it is set to
`manipulation`, single taps can be dispatched immediately.
[1] https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action?v=control#Values
[2] …
=> Implement `touch-action` and its values

src/Css/Elements.elm
[Issue 271](https://github.com/rtfeldman/elm-css/issues/271)
`typeSelector` can help to have missing elements right away. While appropriate changes will be emplemented.
=> Exposed all functions including `typeSelector`.

tests/Properties.elm
This covers the issue described in https://github.com/rtfeldman/elm-css/issues/264, and demonstrates that using `!important` does give the expected result when used with `asPairs`.
I wrote this while investigating that issue, to ensure that the correct result was being produced at that level when `!important` is used. As can be seen this already passes, so feel free to close this if you don't think it adds any value. Thanks
=> Add test case for issue #264

src/Css.elm, tests/Properties.elm, tests/Selectors.elm
This PR adds support for the other possible values for the `white-space` property; previously only `nowrap` was supported. In particular this should resolve https://github.com/rtfeldman/elm-css/issues/285. Hopefully I've done this correctly, I don't fully understand all this dark type system magic yet :slightly_smiling_face:.
=> Add support for more white-space values

src/Css.elm, tests/Properties.elm
Added some missing doc comments, temporarily reverted `whiteSpace normal` support in order to allow for a `MINOR` release. (I'll revert it back for a future 10.0.0 release.)
=> 9.1 Release

src/Css.elm
`text-justify` is an invalid `text-align` value, but `justify` is valid and we did not support it before.
=> Correct text-justify to justify (fixes #293)

src/Css/Media.elm, src/Css/Preprocess.elm, src/Css/Structure.elm, src/Css/Structure/Output.elm, tests/Fixtures.elm, tests/Media.elm, tests/Tests.elm
This revises the media query API a bunch.
Some things it does:
Reading up on [`only`](https://stackoverflow.com/questions/8549529/what-is-the-difference-between-screen-and-only-screen-in-media-queries/14168210#14168210), its basic purpose is to prevent older browsers which do not support media queries from breaking. Having older browsers not break seems always desirable, so the only reason not to use `only` across the board is to save 5 characters of emitted CSS. Especially given how well `@media only` will gzip, I don't think that's enough to justify adding complexity to an already complex API.
e.g. `tv`, `aural`, `embossed`...
Previously it was possible to do things like `[ or, or, or, or ]` - now `or` & `and` take exactly 2 media queries as arguments (and `not` takes 1 argument), so …
=> Revise media queries

src/Css/Media.elm, src/Css/Structure.elm, src/Css/Structure/Output.elm, tests/Fixtures.elm, tests/Media.elm, tests/Tests.elm
This implements #307.
There were no real surprises in the implementation.
I considered renaming `Expression` to `Feature` or `MediaFeature` -- technically `Expression` is the correct term, but `Feature` might be more intuitive. What do you think?
There is a choice in how we render `media [ all [color] ] [ ... ]`:
1. `@media (color) { ... }`
2. `@media only all and (color) { ... }`
Having read [this SO answer](https://stackoverflow.com/questions/8549529/what-is-the-difference-between-screen-and-only-screen-in-media-queries/14168210#14168210), I think both should be ignored by old browsers so it shouldn't matter. I went with option (1).
=> Media query API

src/Css.elm, tests/Fixtures.elm, tests/Tests.elm
Perspective value should be of type length or none, as noted [here](https://developer.mozilla.org/en-US/docs/Web/CSS/perspective).
=> Fix perspective transform.

src/Css/Foreign.elm, src/Html/Styled.elm, src/Html/Styled/Attributes.elm, src/Html/Styled/Events.elm, src/Html/Styled/Keyed.elm, src/Html/Styled/Lazy.elm, src/VirtualDom/Styled.elm
So, to introduce `Svg.Styled` (#339) we need at first to move `Html.Styled.Internal` functionality to some common place. This PR replaces it with the `VirtualDom.Styled` module which should now serve as a base for `Html.Styled` and `Svg.Styled`.
If the idea is OK, we should also discuss whether this module should be exposed. If yes, we should add documentation and clean up its API:  `makeSnippet` function should be moved to another place; `getClassname` function and `Property` constructor shouldn't be exposed. They are currently exposed because `Html.Styled.css` function needs to render classes as the `className` _property_ and `Svg.Styled.css` will need to use the `class` _attribute_, so we'll need to find a better way how to achieve that.
=> Replace Html.Styled.Internal with VirtualDom.Styled

src/Css.elm, src/Html/Styled/Internal.elm
Fixes #337
Choose the last one in the list, to be consistent with what the `style` attribute does in this situation.
Unlike the `style` attribute, these do not stack. The last one "wins."
=> Only acknowledge one `css` attribute per element

src/VirtualDom/Styled.elm
@rtfeldman `lazy2` and `lazy3` probably still suffer from #348 since you've used anonymous functions there.
=> Fix lazy2 and lazy3

.travis.yml, appveyor.yml, tests/Arithmetic.elm
Every now and then, when I ran the arithmetic tests with a certain seed, it would fail because the 3rd number would be `0`.
There was a catch for the second number being `0`, but I also added it for the third number.
The test would do `number1 |/| number2 |/| number3 |/|`.
=> Fix divide by zero error in arithmetic tests

src/Css.elm, src/Css/Foreign.elm, src/Css/Preprocess.elm, src/Css/Preprocess/Resolve.elm, src/DEPRECATED/Css/File.elm, src/VirtualDom/Styled.elm, tests/Compile.elm, tests/TestUtil.elm, tests/Tests.elm
As part of the plan to make doing things in realtime first-class, I'm taking out the concept of warnings. These add a lot of overhead at runtime, and were a nice-to-have at build time anyway; there are other build-time tools that can check compiled CSS for validity.
=> Remove warnings

src/Css.elm, tests/Compile.elm, tests/Media.elm, tests/Properties.elm, tests/Selectors.elm, tests/Styled.elm, tests/Tests.elm
Removes the space after `:` in e.g. `display: none` (making it `display:none` instead) since we're doing things at runtime now and don't want to send all those whitespace bytes to critical CSS for the sake of pretty printing.
Depends on https://github.com/rtfeldman/elm-css/pull/368 - do not merge until that is merged!
=> Remove key-value space

src/Css.elm, src/Css/Preprocess.elm, src/Css/Structure.elm, src/Css/Structure/Output.elm
This will reduce allocations until we have automatic unboxing of single-constructor union types. At that point, this can be reverted with no runtime downside!
=> Use `type alias` for `Property`

src/Css/Transitions.elm
borderBottomWidth functions were using BorderBottomRightRadius instead of BorderBottomWidth
=> Fix bug with borderBottomWidth functions using incorrect Animatable

src/Css.elm
fixed mistyped function name for linearGradient2, removed % symbol from pct
=> linearGradient doc fix

src/Css.elm, tests/Fixtures.elm, tests/Tests.elm
This fixes the bug described in issue #335  . The fix seems a little naive to me. It looks like a value of type `AngleOrDirection` will have an `angle` field when it is of type `Angle`. The other idea was to use the presence of this field on the `dir` argument to infer an angle or direction value . But since it looks like the built-in direction values are only used in the context of a gradient, adding `"to"` to the value was easier. Let me know if this assumption is incorrect. 
The `mocha *.js` part of `npm test` fails for me. The error message is `Elm compiler "/Users/maxhallinan/Stuff/elm-css/tests" did not have permission to run. Do you need to give it executable permissions?`. This test fails on master too. Unfortunately, I do not have time to debug this now but it does not seem …
=> Compile `AngleOrDirection` to correct CSS string

src/Css/Foreign.elm, src/Css/Structure.elm, src/Css/Structure/Output.elm, tests/Fixtures.elm, tests/Tests.elm
This combinator allows for extending a selector with additional [attribute selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors)
```elm
import Css exposing (display, none)
import Css.Foreign exposing (withAttribute, typeSelector)
typeSelector "custom-element"
[ withAttribute "data-custom-attribute" [ display none ]
, withAttribute "data-custom-attribute=true" [ display none ]
]
```
results in
```css
custom-element[data-custom-attribute] {
display:none;
}
custom-element[data-custom-attribute=true] {
display:none;
}
```
This is just meant as a primitive for building inline attribute selectors. Type-safe versions of the various attribute value comparison operators can be added later or separately.
=> Add withAttribute

src/Css.elm
The docs have a small error here
> Snake-case CSS names become camelCase names in elm-css.
because CSS names are kebap case (dashes) not snake case (underscores).
=> fix docs typo form snake to kebap case

src/Css.elm
This builds on #395, adding `backgroundImage`. The commits for this depend on linear gradients to reach full coverage as is in master, and start at b7a4333.
8b1250d is new coverage of the CSS spec. I added it as I was thinking about it (since you can't have multiple `none`s) but feel free to cherry-pick/drop. 😄
progress for #392
=> Phantom types background image

src/Css.elm
Restored properties:
- `overflow`
- `overflowX`
- `overflowY` 
- `overflowWrap`
=> Rewrite overflow and overflowWrap using phantom types approach

src/Css.elm
Add properties relating to tables: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Table
Also adds a couple of overlooked exports from #403.
=> Phantom types: table properties

src/Css.elm
Various positioning related properties and values added.
@rtfeldman I wanted to ask you about the docs changes I made to `fixed`. `fixed` is a value used by a few other properties, but its docs only mentioned `background-attachment`. I simply added them all into the docs for `fixed`. LMK if you'd like it solved in a different way 👍 .
=> Add phantom types for position and z-index

.travis.yml
tests aren't supposed to work for phantom-types until the end, so why don't we disable 'em until that integration work happens? As an external contributor, I'd love to know if my branch is actually passing, and as the author I'm sure you'd appreciate folks taking care of errors on their own 😄
=> make travis work for the phantom-types branch

src/Css.elm
This adds `background-repeat`
Progress on my bits of #392
=> Phantom types: background-repeat

src/Css.elm
Hi @rtfeldman! I'm glad to show `border` properties as a part of #392 here. Please take a look.
=> Phantom border

src/Css.elm
=> Add word-break

src/Html/Styled.elm
(paired with @avh4)
Previously:
when using `Html.Styled.styled`, with `tesk9/accessible-html-with-css`, `styled` would coerce all subtypes into `Html Never`
This PR generalizes `Html.Styled.styled` such that it can still return `Html msg`
=> Styled.styled supports tesk9/accessible-html-with-css by being more general

.travis.yml, src/Css.elm
`wordBreak` currently has the wrong signature in phantom-types :cry: This fixes it. I *think* it's right! But always good to have a second set of eyes on it 😄
Also adds a Travis check for type signatures so future issues on phantom-types should fail the build.
=> Phantom types: fix wordbreak

src/Css.elm
=> Add visibility

src/Css.elm
This adds `backgroundSize` and `backgroundSize2` for #392. Commits for this start at 48733cd, and I'm happy to rebase onto phantom-types when/if #419 is merged.
I was going to add `backgroundSizes` to go along with `backgroundImages`, but I can't figure out a good way of doing the types. Essentially, we need to be able to have all these properties:
```css
/* valid */
background-size: cover;
background-size: 100px;
background-size: 100px, cover;
background-size: 100px 20px, cover;
/* invalid */
backgrouns-size: cover cover;
background-size: 100px 20px, cover cover;
```
---
=> Phantom types: background-size

src/Css.elm
Hi @rtfeldman! The next bulk of properties as a part of #392 are here 😀 Please take a look.
=> Phantom border radius

src/Css.elm
=> Phantom Types: Add fill

src/Css.elm
Hello @rtfeldman! The PR includes implementation of `padding*` rules as a part of #392 
Please take a look.
=> Phantom padding

src/Css.elm
Hello @rtfeldman! The PR includes implementation of `margin*` (changes are very close to #425) rules as a part of #392 
Please take a look.
=> Phantom margins

src/Css.elm
Hi @rtfeldman! There is implementation of `text-decoration*` property with some value as a part of #392 
Please take a look.
=> Text Decoration properties and values has been implemented and exposed

src/Css.elm
This adds `borderImageOutset`, `borderImageOutset2`, `borderImageOutset3`, `borderImageOutset4`, `borderImageWidth`,  `borderImageWidth2`,  `borderImageWidth3` and  `borderImageWidth4` for https://github.com/rtfeldman/elm-css/issues/392.
It also changes the type of pure numeric value that can be passed to `zIndex` from `num` to `int`.
=> Phantom types: border-image-outset and border-image-width

CHANGELOG.md, src/Css.elm
I added these before realizing it wasn't a great idea to add experimental properties. 😅
=> Remove experimental border properties

src/Css.elm
This adds the following properties with values:
=> Phantom types: columns

CHANGELOG.md, src/Css.elm
It's experimental and only FF supports it.
https://caniuse.com/#feat=css-dir-pseudo
=> Remove `dir`

src/Css.elm
Convert `boxSizing` to use phantom types #392.
=> Phantom types: add boxSizing

src/Css.elm
=> Phantom types new properties

src/Css.elm
Found this little bug when I was working on the `textShadow` implementation. Color was not present in the output.
=> Phantom Type: Add missing color to box-shadow output

CHANGELOG.md, elm-package.json, src/Css.elm, src/Css/Global.elm, tests/CompileFixtures.elm, tests/Fixtures.elm, tests/Media.elm
For 0.19 the type of `class`, `id`, `animationName`, and `animationNames` will need to change - they will have to accept a `String` instead of any type since `toString` will no longer accept any type.
This changes that, and removes the dependency on `elm-css-util`, since helping with this scenario is the only reason that package existed.
=> Remove elm-css-util dependency

src/Css.elm
Hi, I was going through the [documentation](http://package.elm-lang.org/packages/rtfeldman/elm-css/latest/Css) and found this typo.
=> Fix typo in docs

src/Css.elm
I didn't see an easy way to write test for this into the existing test strategy, but I'm happy to take another look with some pointers!
I hit this bug when creating "theme" colors for my site, then trying to lighten/darken them by adjusting the `hsla` lightness. `elm-css` only preserves the rgb values, which takes a bit of conversion to round trip through `hsla`, resulting in this bug.
Thanks!
Augustus
=> Fix #461: degree/radian mismatch for `hsla` hue

.travis.yml, package-lock.json, package.json, src/Css.elm, src/Css/Preprocess/Resolve.elm, src/Css/Structure.elm, src/Css/Structure/Output.elm, src/Html/Styled/Attributes.elm, src/Html/Styled/Events.elm, src/VirtualDom/Styled.elm
Looks like `elm-format@rc` doesn't exist anymore, and IMO it'd be better to explicit about what version of Elm we're using now that 0.19 is out (:tada:).
=> fix CI for phantom types

0.18-src/Css.elm, src/Css.elm
The output for "seconds" should be `"s"`, not `"sec"`
h/t @lukewestby for reporting this!
=> Fix "seconds"

0.18-src/Css/Global.elm, src/Css/Global.elm
Just a quick documentation fix.
Also, I the old snippet kinda makes me laugh since it looks like we are about to do some good ol' OOP. (`class Foo`)
=> Docs fix: class no longer accepts custom types

src/Css.elm
- (n/a) Each Value is an open record with a single field. The field's name is the value's name, and its type is Supported. For example foo : Value { provides | foo : Supported }
- (n/a) Each function returning Style accepts a closed record of Supported fields.
- (n/a) If a function returning Style takes a single Value, that Value should always support inherit, initial, and unset because all CSS properties support those three values! For example, borderFoo : Value { foo : Supported, bar : Supported, inherit : Supported, initial : Supported, unset : Supported } -> Style
- (n/a) If a function returning Style takes more than one Value, however, then none of its arguments should support inherit, initial, or unset, because these can never be used in conjunction with other values! For example, …
=> Phantom Types: add :disabled

src/Css.elm
=> width, min-width, and max-width

src/Css.elm
=> Added justifyContent

src/Css.elm
=> Add `list-style-position`

src/Css.elm
=> Line height letter spacing

src/Css.elm
It's been a while, but I've taken some time to add a bunch more properties to the Phantom Type branch. This should take us a lot towards releasing a new version with phantom types.
=> Phantom Types: add a bunch more properties

src/Css.elm
This possibly a typo or find-replace error in the W3 documentation.
The values in the specification indicate a `stupid` value. But, the
issue below it describes it as `fallback`.
See: https://www.w3.org/TR/fill-stroke-3/#stroke-linejoin
=> Rename `stupid` to `fallback`

src/Css.elm
I'm working on CSS properties that have multiple functions with the same name and a number as suffix (e.g. padding2, padding3) and improving their documentation for clarity.
=> Phantom Types: Improve padding documentation

src/Svg/Styled/Keyed.elm, src/VirtualDom/Styled.elm
SvgKeyed used keyedNode instead of keyedNodeNS. The virtual DOM
therefore treated the Svg as a generic element.
The fix reflects the fix made by Evan in the elm/svg package.
https://github.com/elm/svg/blob/master/src/Svg/Keyed.elm
Also, this closes issue #504.
The fix originated from a Keyed Svg of mine that contained no width or height. I noticed that the browser treated it as a generic node instead of an Svg. I compared rtfeldman/elm-css to elm/svg and noticed the difference.
=> Fix SvgKeyed

elm.json, src/Css.elm
The current phantom-types branch does not build. 
**Skinney**/murmur3 **2.0.8** has been re-released as **robinheghan**/murmur3 **1.0.0**.
There were two currencies of `fallback`. I merge the documentation and deleted one of them as they were the same.
=> Phantom types: Fix build

src/Css.elm
I've based this on the, already present, `box-shadow` property which is almost the same except for the `inset` and `spread-radius`.
=> Phantom Types: Add textShadow

src/Css.elm
Hi, first PR here so feedback is welcome.
**Important notes / feedback likely needed**
1. I replaced `displayFlex` by `display flex_` as it seems that `underscore` won the namespace war for now. Tell me if I'm wrong.
2. I included a fix to "close" the "open" record parameter of `alignItems` and `all` (in passing) as they seemed wrong (their value record was parameterized on `accepts`). But I may have misunderstood something so tell me if I should remove this modification.
3. I did not  include yet overflow and baseline alignment for `justifyContent` and `alignContent` as they are still in a draft specification and are not well supported by all browsers. However `alignItems` already implements them partially (overflow alignment is limited to `safe center` or `unsafe center` but `center | …
=> Phantom types: add most missing flexbox functions/values

src/Css.elm, src/Css/Colors.elm
When writing the [flexbox phantom types](https://github.com/rtfeldman/elm-css/pull/452), I noticed that using a value that can include a [CSS length](https://developer.mozilla.org/en-US/docs/Web/CSS/length) was quite error prone.
It required a copy/paste from another similar function or from the spec and double checking each supported value in the record, without [forgetting](https://github.com/rtfeldman/elm-css/blob/32f1b4d0ff836652cb7a6d9ccdbfd600dc70270b/src/Css.elm#L11087) to add `zero` and `calc`. Also if a new unit is added one day (as `rem` or others before), it would be quite difficult to be sure to have updated all functions that support a `length` as they are not easily identified (there are also some inconsistencies in the order of the record values for example). 
At last, …
=> Phantom types aliases proposal

src/Css/Preprocess/Resolve.elm, src/Css/Structure.elm, src/Css/Structure/Hash.elm, src/Css/Structure/Output.elm, src/Hash.elm, src/VirtualDom/Styled.elm, tests/Styled.elm
I recently setup an elm-css benchmark based on code from our production code base, and after profiling said benchmark, I discovered that string concatination and hashing is where elm-css spends most of its time.
This PR improves the performance of elm-css by reducing the amount of text that has to be hashed in order to generate a classname.
From my testing, this improves performance by 10-15% depending on the browser being run.
The benchmark I ran can be found here: https://github.com/robinheghan/elm-css-playground
Check out the `reduce-hash-content` branch to test this particular optimization in isolation.
When combined with the changes in #544 , I see performance improvements in the 30-40% range, depending on the browser being run.
=> Reduce hash content

src/Css/Animations.elm
The example suggested keyframes wanted `List ( Int, Css.Animations.Property )` but it actually wants `List ( Int, List Css.Animations.Property )`.
=> Fix readme for animationName property

src/Css.elm, src/Css/Animations.elm, src/Css/Internal.elm, src/Css/Preprocess/Resolve.elm, src/Css/String.elm, src/Css/Structure/Hash.elm, src/Css/Structure/Output.elm, src/Html/Styled/Attributes.elm
I recently setup an elm-css benchmark based on code from our production code base, and after profiling said benchmark, I discovered that string concatination and hashing is where elm-css spends most of its time.
This PR improves the performance of elm-css by combining several map+join and filter+join operations into a single operation. It also replaces certain `String.join ""` calls with normal string concatination using the ++ operator.
From my testing, this improves performance by 15-20% depending on the browser being run.
The benchmark I ran can be found here: https://github.com/robinheghan/elm-css-playground
Check out the `reduce-string-joins` branch to test this particular optimization in isolation.
=> Optimize string concatination.

elm.json, src/Css/Structure/Hash.elm, src/Hash.elm, tests/Keyframes.elm, tests/Styled.elm
After talking to Richard, we agreed to hold back the hash-function change. FNV is a slightly worse hash than Murmur3, and elm-css doesn't have a way to handle hash collisions. It's safer to stick with Murmur3, for now.
=> Replace fnv with murmur3

src/Css/Global.elm, src/VirtualDom/Styled.elm
Fixes #557
Using `display: none;` seems like a good default and still fixes #542.
I think it might be worth adding a class like `elm-css-style-wrapper` in case the display: none is not good or if someone needs to override the style as @ymtszw needed.
If that's the case using the following will allow to override even the inline `display: none;` [^1]
```css
.elm-css-style-wrapper[style] { 
/* your style */
}
```
I based this change on 17.0.1 in case a 17.0.2 is wanted.
[^1]: [Override Inline Styles with CSS](https://css-tricks.com/override-inline-styles-with-css/)
=> Set display: none and add elm-css-style-wrapper class

elm.json, examples/html-styled/Main.elm, examples/html-styled/elm.json, package.json, src/VirtualDom/Styled.elm
fixes #543 
When `unStyling` nodes elm-css internally was using `VirtualDom.property "className" ...` which was causing runtime exceptions for svg elements. The property "className" is deprecated for svg elements and was the reason for the exception.
This meant that anytime you would set css inside of any svg element, an exception would be thrown and cause the page to not render correctly. 
Using `VirtualDom.attribute "className" ...` properly sets the value and stops the exception from happening.
- Updated elm examples
- Replaced dead package
- Updated elm-test
=> fix: Runtime exception when using css in SVG elements

src/VirtualDom/Styled.elm
fixes #563 
Using attribute does set the css class correctly however the attribute
name needs to be class instead of className.
Using className will set classes as `classname` in dom nodes and
`className` in svg nodes which is incorrect.
Here we can see the incorrect attribute name. On the left we should be seeing a handsome `elm-select`. No styles are applied.
And with correct class.
=> fix: Set attribute value to class

src/Html/Styled.elm
Broken text is on https://package.elm-lang.org/packages/rtfeldman/elm-css/latest/Html-Styled - top of the page. I'm guessing it's an indentation issue.
=> Fixed Styled.elm docstring issue

examples/html-styled/Main.elm, src/VirtualDom/Styled.elm, tests/Styled.elm
fixes #564 
17.0.4 fixed a bug that was causing DOM exceptions by changing the way we were updating styles to use `VirtualDom.attribute "class" ...` instead of `VirtualDom.property "className" ...`.
This was due to svg elements not liking the `property "className"` method which is a known phenomenon in the html spec.
Some random stack overflow post that is probably true: https://stackoverflow.com/questions/43750395/how-to-add-a-class-in-a-svg-element-circle-using-javascript
However, whilst the pesky exception was fixed there were some unintended side effects you can read about in this issue #564.
- Revert the `extractUnstyledAttribute` function to behave as it used to for html elements.
- Create an `extractUnstyledAttributeNS` function to set styles for svg nodes using the `attribute` …
=> fix: setting styles with attribute for svg elements

CHANGELOG.md
Remove an empty line between header and content.
=> Fix broken table in the CHANGELOG.md file

src/Css.elm, src/Css/Internal.elm, src/Css/Preprocess.elm, src/Css/Preprocess/Resolve.elm, src/Css/Structure.elm, src/Css/Structure/Output.elm
> Ideally, this would be `type Property = Property String` - but in order to reduce allocations, we're doing it as a `type alias` until union types with one constructor get unboxed automatically.
Trying to realize your years-old wish. Feel free to ignore, I just couldn't help myself :sweat_smile:
=> Make Css.Structure.Property a custom type

src/Css/Structure.elm
I noticed that this argument was unused and could therefore be removed. I have no clue what the argument was meant for in the first place :shrug: 
There is a lot of dead code in this project (even excluding the deprecated folder). Would you care for a clean up PR?
=> Remove unused code

src/Html/Styled.elm, src/Svg/Styled.elm, src/VirtualDom/Styled.elm
Fixes #569
Happy to make any changes, and to take suggestions for better documentation of the function :slightly_smiling_face:
=> Add toNonceUnstyled functions for CSP nonce support

src/VirtualDom/Styled.elm
Fix #558
After discussion on #558 with @rtfeldman we decided that the cat is out of the bag on restricting users from being able to apply multiple `css` attributes to a single node. This has already been allowed for child nodes of the node passed to `toUnstyled` so this PR simply allows this on the root node as well (and we get to pull some code 😁). 
This will cause less confusion for users of this library.  Previously converting a node to be lazy could cause `css` styles to be dropped.
=> Allow multiple css attributes on root node

src/Css.elm
Remove extraneous parenthesis to fix documentation visualizaiton on packages.elm-lang.org
=> Fix documentation for rgb, rgba, hsl, hsla, hex
