rtfeldman/elm-css

- elm-package.json
- examples/src/Stylesheets.elm
- src/Css.elm
- src/Css/File.elm
- test/Tests.elm
> Move functions dealing with CSS files to Css.File

- README.md
- bin/elm-css
- package.json
Super basic at this point, but enables generating .css files from the command line.
> Add elm-css binary

- README.md
- examples/src/HomepageCss.elm
- src/Css.elm
- test/FixturesCss.elm
- test/Tests.elm
- test/fixtures/homepage-compiled.css
Implements some of https://github.com/rtfeldman/elm-css/issues/15 and transitions from `5 px` to `(px 5)`
> Add basic Borders

- src/Css.elm
This will scale better than calling them out in places where they could be used.
> Be more explicit about intentionally unsupported keywords

- src/Css.elm
- src/Css/File.elm
- src/Css/Util.elm
- src/Style.elm
- test/FixturesCss.elm
This way if you like, you can use a union type for your namespace too.
> Allow any type for the namespace, not just String

- src/Css.elm
> Margin things

- src/Css.elm
For #22 
I also added a couple missing type annotations to get my linter to stop complaining, and ran Css.elm throught elm-format.
Thanks!
> Padding things

- src/Css.elm
- test/FixturesCss.elm
- test/Tests.elm
Tricky because one is a property and the other is a value...but totally doable!
> Implement property/value dualities for position, text-align, and vertical-align

- elm-package.json
- examples/src/HomepageCss.elm
- src/Css.elm
- src/Css/Elements.elm
- test/FixturesCss.elm
> Split out Css.Elements

- src/Css.elm
- test/FixturesCss.elm
- test/Tests.elm
This is everything except `transform-origin`, still haven't thought all the way through overlaying `left | right | top | bottom` with lengths.
Thanks!
Ref #23
> Transform things

- src/Css.elm
Completes https://github.com/rtfeldman/elm-css/issues/24
> Finish text

- src/Css.elm
- src/Css/File.elm
- test/FixturesCss.elm
- test/Properties.elm
This turns out not to be awesome after all.
> Stop doing namespace as a type parameter

- src/Css.elm
- src/Css/Compile.elm
- src/Css/Declaration.elm
- src/Css/File.elm
- test/Compile.elm
- test/CompileFixtures.elm
- test/Properties.elm
- test/TestUtil.elm
- test/Tests.elm
- test/elm-package.json
* Generate warnings if RGB or RGBA values are outside acceptable numeric bounds
* Use elm-check to verify that this is working properly
> Warn for invalid RGB values

- src/Css.elm
- test/Fixtures.elm
- test/FixturesCss.elm
- test/Tests.elm
Added line-height, font-family, font-style, font-size, font-weight and font-variant together with various supporting keyword such as bold, serif, etc. They're mostly complete, there might be some legal CSS not accounted for. 
Commented the unsupported medium function and add medium as a valid font weight attribute.
> Issue #14 and #20

- .travis.yml
- appveyor.yml
- package.json
> add node version requirement

- README.md
- readme-example/.gitignore
- readme-example/elm-package.json
- readme-example/src/Main.elm
- readme-example/src/MyCss.elm
- readme-example/src/Stylesheets.elm
The examples in the readme were not complete. They didn't give me enough information to make elm-css work for me.
I think this adds enough. (addresses issue 87 among other things)
In addition, I added a directory containing the code for the README to prove that it compiles.
> Flesh out README with all the code needed to make this work

- src/Css/Preprocess/Resolve.elm
- test/Fixtures.elm
- test/TestRunner.elm
- test/Tests.elm
Fixes https://github.com/rtfeldman/elm-css/issues/99
> Fix some combinator bugs

- src/Css/Elements.elm
I'm trying to port http://getskeleton.com/ to Elm, as a field-test. This is one of the missing pieces I've come up against.
> Adding h5 and h6 selectors.

- examples/src/HomepageView.elm
> Fix example by adding missing argument to Html

- src/Css.elm
I deleted my old fork to clean it out and start over. I've implemented the changes now.
> Updated Post-1.0 Keywords

- src/Css.elm
> Fix: rgba was not setting alpha in Color

- examples/src/HomepageCss.elm
- src/Css.elm
- tests/Properties.elm
- tests/fixtures/homepage-compiled.css
Adding the box-shadow property in Css properties.
> Box shadow

- src/Css.elm
- tests/Properties.elm
Fixes #175. I ran into this myself in the past, might as well do a fix as others seem to be running into too 😆
> Fix line-height not accepting numbers

- src/Css.elm
- tests/Properties.elm
Fixes https://github.com/rtfeldman/elm-css/issues/178
> Support font-weight: normal

- README.md
Most opened issues or questions on Slack are about missing properties that can be resolved using property function.
Examples: #186 #174 and some in Slack
So including this inside the README might help.
> Explain how missing properties can be defined

- .travis.yml
- appveyor.yml
- examples/elm-package.json
- tests/elm-package.json
Started debugging the test issue of failing tests after the 0.18 upgrade. And found an example issue in the process.
> Fix tests after 0.18 upgrade

- src/Css.elm
- tests/Arithmetic.elm
- tests/Tests.elm
Fixes https://github.com/rtfeldman/elm-css/issues/184
> Fix arithmetic operator output

- src/Css.elm
> Fixed wrong corresponding css names in some documentation of functions

- elm-package.json
- src/Css/Colors.elm
This closes https://github.com/rtfeldman/elm-css/issues/208
> Exposing colors

- src/Css.elm
- tests/Properties.elm
box-shadow: inset offset-x offset-y blur-radius spread-radius color
> Add property: boxShadow6

- src/Css.elm
- src/Css/Elements.elm
Noticed #139 mentioned a desire for SVG elements. I've been using a couple of these on a project for a couple months, figured I'd fill out the rest of the basic shapes here. Not sure if there are other specific elements people might need, if there are just let me know and I can add them.
I also added `fill` property and `blockquote` element here.
> Added SVG basic elements

- .travis.yml
- README.md
- readme-example/src/Stylesheets.elm
It was out of date.
This also updates CI to verify that the examples compile.
> Update readme-example to 0.18

- src/Css/Colors.elm
> Add Examples for Colors

- index.js
> Support nested modules

- src/Css.elm
Not a big issue, just fixing some broken links. Thanks :slightly_smiling_face:
> Fix some broken links in docs

- src/Css.elm
Finger throttling has these things I guess. Kudos.
> Fix small typo in variable type

- index.js
Temporary files were created but was not cleaned up after. So I forced cleanup.
> Forced cleanup of temporary files.

- index.js
Very minor, just removing a potentially confusing comment that is no longer relevant :slightly_smiling_face:.
> Remove obsolete comment

- elm-package.json
- src/Css.elm
- src/Css/Media.elm
- src/Css/Structure.elm
- src/Css/Structure/Output.elm
- tests/Fixtures.elm
- tests/Media.elm
- tests/Tests.elm
I took https://github.com/rtfeldman/elm-css/pull/207 and updated it
> add full media query support

- src/Css/Colors.elm
It's just a small change. Less than I should do to say thank you for such a helpful project!
> Added 'white' predefined color as also defined at http://clrs.cc/

- js/compile-all.js
> Propagate compile errors from node-elm-compiler

- README.md
- elm-package.json
- src/Css.elm
- src/Html/Styled.elm
- src/Html/Styled/Attributes.elm
- src/Html/Styled/Internal.elm
- src/Svg/Styled.elm
- src/Svg/Styled/Attributes.elm
- src/Svg/Styled/Events.elm
- src/Svg/Styled/Internal.elm
- src/Svg/Styled/Keyed.elm
- src/Svg/Styled/Lazy.elm
> Move Html.Attributes.styled to Html.Styled module; add Svg.Styled modules.

- src/Html/Styled/Lazy.elm
Fixes https://github.com/rtfeldman/elm-css/issues/348
> Fix lazy API

- src/Css.elm
- tests/Properties.elm
https://github.com/rtfeldman/elm-css/issues/14
> implemented table-layout

- src/Css/Transitions.elm
Adapted from:
https://github.com/robrtle/elm-css/blob/transition/src/Css/Transitions.elm
> Add transitions

- src/Css/Transitions.elm
* Expose `Transition`
* Make `Transition` a union type
* Replace code duplication with helpers.
> Refactor transitions

- src/Css.elm
- src/Css/Preprocess.elm
- src/Css/Structure.elm
- src/Css/Structure/Output.elm
This gets us closer to representing `Property` as a `String` in memory!
> Remove separate tracking of !important

- src/Css.elm
- src/Css/Preprocess.elm
- src/Css/Preprocess/Resolve.elm
- src/Css/Structure.elm
- src/Css/Structure/Output.elm
Depends on https://github.com/rtfeldman/elm-css/pull/367 - do not merge until that is merged!
> Merge key-value storage

- src/Css/Preprocess/Resolve.elm
- src/Css/Structure.elm
- tests/Media.elm
Fixes #352
@tolgap Thanks for identifying the source of the problem!
> Fix `withMedia`

- src/Css/Foreign.elm
- src/Css/Media.elm
- src/Css/Preprocess.elm
- src/Css/Preprocess/Resolve.elm
- src/Css/Structure.elm
- src/Css/Structure/Output.elm
- src/DEPRECATED/Css/File.elm
- src/VirtualDom/Styled.elm
Fix a bunch of miscellaneous stuff.
> Fix some stuff elm-analyse reported

- src/Css/Transitions.elm
Submitting a PR with documentation for CSS.Transitions to resolve #362
> Adding documentation for CSS.Transitions

- src/Html/Styled/Attributes.elm
> Clarify `Html.Styled.Attributes.style` docs

- src/Css.elm
I started to do `backgroundImage` but couldn't implement all the values without linear gradients. So this is done.
P.S. It was *so* tempting to name `toCorner` `to2` 😜
#392
> phantom types: linear gradient

- src/Css.elm
> Implemented textRendering and its values

- src/Css.elm
Hey! Implemented `textOrientation` and its values: `mixed`, `sideways`, and `upright`. There was no suitable link to css-tricks' almanac so I used MDN.
> Implemented textOrientation and its values

- src/Css.elm
progress on the background stuff in #392.
(P.S. not all the ones you've marked me as having done there are done yet. This adds `background-position`, two more PRs will add `background-repeat` and `background-size`.)
> Phantom types: backgroundPosition

- src/Html/Styled/Lazy.elm
- src/Svg/Styled/Lazy.elm
- src/VirtualDom/Styled.elm
> [0.19] Improve Lazy API, add more lazyN functions

- src/Css.elm
This fixes some missing exposing, unused variables, redefining of variables, and typo's in the code.
> Phantom types fixes

- src/Css/Global.elm
> Add details and summary to Css.Foreign

- src/Html/Styled.elm
- src/Svg/Styled.elm
> Make *.Styled.styled lazy

- src/Css.elm
Note that this is in the documentation comments only.
> Correct attiibute into attribute

- 0.18-src/Css.elm
- 0.18-src/Css/Animations.elm
- 0.18-src/Css/Colors.elm
- 0.18-src/Css/Global.elm
- 0.18-src/Css/Internal.elm
- 0.18-src/Css/Media.elm
- 0.18-src/Css/Preprocess.elm
- 0.18-src/Css/Preprocess/Resolve.elm
- 0.18-src/Css/Structure.elm
- 0.18-src/Css/Structure/Output.elm
- 0.18-src/Css/Transitions.elm
- 0.18-src/Hash.elm
- 0.18-src/Html/Styled.elm
- 0.18-src/Html/Styled/Attributes.elm
- 0.18-src/Html/Styled/Events.elm
- 0.18-src/Html/Styled/Internal.elm
- 0.18-src/Html/Styled/Keyed.elm
- 0.18-src/Html/Styled/Lazy.elm
- 0.18-src/Svg/Styled.elm
- 0.18-src/Svg/Styled/Attributes.elm
- 0.18-src/Svg/Styled/Events.elm
- 0.18-src/Svg/Styled/Internal.elm
- 0.18-src/Svg/Styled/Keyed.elm
- 0.18-src/Svg/Styled/Lazy.elm
- 0.18-src/VirtualDom/Styled.elm
- elm-package.json
- elm.json
- src/Css.elm
> Add some animation properties

- .travis.yml
Should remove the red crosses from CI!
> update travis.yml to elm 0.19.1

- elm.json
- src/ElmCssVendor/Murmur3.elm
- src/Hash.elm
- src/VirtualDom/Styled.elm
Fixes https://github.com/rtfeldman/elm-css/issues/527
We can un-vendor once it's been published under Robin's new account!
> Vendor Murmur3 for now

- src/Css.elm
Fixing bugs that I have detected by the use of a modified test-suite.
Added a bit of documentation along the way.
> Phantom types: Fix bugs and add documentation

- src/Css.elm
- src/Css/Preprocess.elm
- tests/Fixtures.elm
- tests/Tests.elm
This solves the problem I wrote up in #534
> Use new mapProperties function in important
